### ISSUE TITLE
ios asset loading issue

### ISSUE THREAD

**Issue by zabojad** [haxenme/nme#125]
On iOS only:

This below will not make the assets accessible with nme.Assets.getText() (it will return null):

```
	<assets path="app" rename="" include="*" />
```

However this will work:

```
	<assets from="app/" embed="true" >
		<asset name="my-app.html" />
		<asset name="styles/my-app.css" />
		<asset name="styles/themes/default.css" />
(...)
	</assets>
```

The same doesn't happen on Android (first case works on android).

**Comment by thomasuster** [comment]
Hi, I wasn't able to repro. Either the issue is gone or I'm misunderstanding you. I started to construct a unit test to try and narrow this down, the test case ended up being a good one for NME to have, so it's here. Feel free to reopen if this is still an issue for you. https://github.com/thomasuster/NME/commit/ab070751c4049ae05204018c83c074b33e908ba5
