### ISSUE TITLE
How can I speed up pixel access?

### ISSUE THREAD

**Issue by azrafe7** [haxenme/nme#330]
Hi again @hughsando, hope you can help me with this.

I'm currently using get/setPixels in [this lib](https://github.com/azrafe7/hxPixels/blob/4bfd2bff1043cc1616597df260209215f514cabc/src/hxPixels/Pixels.hx#L281-L377) (the approach is similar to as3 lock/unlock), but the performance is not as good as I'd hoped.

Could you suggest a way to improve pixel access performance on neko/cpp?

**Comment by hughsando** [comment]
There are a few things that could be slowing things down.
1. Is do do with how pixels are transferred to/from the native store (however lime stores it) and into haxe.  For example, is it a simple memory copy, or does it do funky stuff with component ordering and alpha multiplications?  This is nothing really to with with your haxe/hxcpp code.
2. The sets/gets and looping.  Here it would be worth checking the generated code to make sure everything is inlined and you are not making function calls on a per-pixel basis.  It might be that you could do the bit-wise manipulations yourself, rather than with the lib.  Could be a speed/convenience tradeoff.

But really the way to tell is to add a native profiler.  Compile in release mode, but with "-DHXCPP_DEBUG_LINK" to get symbols.  On windows, the "Very Sleepy" profiler is free and easy.

**Comment by azrafe7** [comment]
Thanks for the tips. Going to profile it and see what I can find.

2016-06-24 3:04 GMT+02:00 Hugh Sanderson <notifications@github.com>:

**Comment by azrafe7** [comment]
Turns out the bottleneck was in another part of my code. Profiling it and using inline gets/sets instead of calling the functions did improve the speed but very slightly (2 fps).

Closed as not really an issue with the lib, but I'd still love to see if it can be improved significantly (html5 canvas is many times faster)

**Comment by hughsando** [comment]
Are you using openfl or nme?  If it's nme, I can have a look.

**Comment by azrafe7** [comment]
Actually both!

On the test I was using nme and comparing it against openfl (with nme being faster - although by a slight amount - on neko/cpp).

Profiling [this code](https://gist.github.com/azrafe7/7b2bae23d608fe22a38ad3525d42a773) (which uses the mentioned lib, and is really thrown together) is what made me realize that it was my fault (in the sense that pixels manipulations were fast - to some extent - and that the problem was somewhere else in my original program).

(Should also ay that all of this comes out from the GameOfLife's post on the ML)
