### ISSUE TITLE
emscripten status?

### ISSUE THREAD

**Issue by madrazo** [haxenme/nme#452]
Emscripten seems to be a "secret" target since it is not documented. What is its status?

After installing Emscripten compiler from https://kripken.github.io/emscripten-site/docs/getting_started/downloads.html

DisplayingABitmap>haxelib run nme emscripten -toolkit -debug

it first gets the error
Link: ApplicationMain-debug.html
ERROR:root:E:/extensions/nme2017/lib/Emscripten/libnme.a: No such file or directory ("E:/extensions/nme2017/lib/Emscripten/libnme.a" was expected to be an input file, based on the commandline arguments provided)

After building the nme project and trying again, I got another error

Link: ApplicationMain-debug.html
warning: emitted code will contain very large numbers of local variables, which is bad for performance (build to JS with -O2 or above to avoid this - make sure to do so both on source files, and during 'linking')
pre-main prep time: 287 ms
Invalid function pointer called with signature 'viii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)
Build with ASSERTIONS=2 for more info.

Thanks

**Comment by hughsando** [comment]
Support for Emscripten is experimental.  I did have it working at some
stage, but I am not convinced it is worth the effort in the naive form.
I think it would be better if the haxe code could compile straight  to js,
and the nme c++ code compiled via Emscripten to a constant blob of js.  But
this is not as easy as it is, say, with neko because js in a browser does
not (and will not) have finalizers so resources would leak.
I think this can be fixed with careful management of the c++ objects in the
display list, and this is the ultimate form I think Emscripten would be
useful in.

**Comment by madrazo** [comment]
I see. Thanks for the explanation. 
I wish there were a tool to generate wasm directly that handles the issue automatically. 😆

**Comment by hughsando** [comment]
If you compile the whole thing with hxcpp, it could actually work - I just think its missing the benefits of a native JS target.  The bad signature could probably be solved, so it is probably not too far from being usable (with a little effort!)

**Comment by hughsando** [comment]
I just made some changes to hxcpp to get emscripten working again.  Works ok in a few places.
I use "nme emscripten -toolkit" to build/run.

**Comment by hoseyjoe** [comment]
I tried compiling a project but got:
In file included from include\Display.h:6:
`../include\nme/ObjectStream.h:135:13: error: use of undeclared identifier 'printf'
            printf("got object, but wrong type %p\n", obj);`

Not sure if my end or issue

**Comment by madrazo** [comment]
In gitter it was mentioned that you can build "nme.js" from "project "dir using
`haxelib run hxcpp ToolkitBuild.xml -Demscripten -DHXCPP_JS_PRIME`

And then "nme html5" to build DisplayingABitmap for example

**Comment by hughsando** [comment]
I have been working on the "jsprime" target, which is a bit different from the "emscripten" target.
The first one compile the nme C++ files the nme.js, and then the haxe files using the javascript compiler.
The latter compiles the whole thing using emscripten and the hxcpp compiler.
I may have broken the emscripten while working on jsprime.  I will circle back around and see if I can fix emscripten, but if commenting out the line fixes the problem, it would not be a bad fix for now.

**Comment by hoseyjoe** [comment]
JSPrime - html5 is fast to compile (as you would expect since nme is already the JS at this point). 
Emscripten worked fine for me after commenting out 'printf' in above issue. So kudos!

Any idea if there will be any vector based html5?  I am assuming these are all ending in canvas target. So browser zoom will always be bitmap/pixelated.

**Comment by hughsando** [comment]
No, both these solutions require WebGL are are fully hardware-vectorized - no canvas API.
This is because it is pretty much exactly the same code that is on desktop/ios/android.
The pixelation is controlled by the size of the off-screen render target (canvas).  For the jsprime target, I created a nme template for the index.html by hacking the emscripten generated ApplicationMain.html and customizing it - eg making the canvas full screen.  The emscripten target is using the default emscripten logic and html file.  But this should be easy enough to change too.
I will probably change this emscripten output soon - but first I'm going to look at making a mini-preloader which should work for both emscripten and jsprime.

**Comment by hoseyjoe** [comment]
Awesome.

File size is large but I imagine some of that will change.

Do you want issues submitted or is it still too green?

**Comment by hughsando** [comment]
I think it is ready for a few issues - depending on how may you have :)

**Comment by madrazo** [comment]
How do you test for emscripten?
If I do `DisplayingABitmap>nme emscripten`, I get
`Assets.hx:205: [nme.Assets] missing asset 'assets/nme.png' of type BitmapData`
on the browser

**Comment by hughsando** [comment]
emscripten is a bit stuffed at the moment because I have been working
mainly on jsprime(html5) which I think I prefer because it is so fast to
compile.
Although a quick test seemed to work for me, so I'll have to think about it.

**Comment by madrazo** [comment]
Tried again and it worked. I think that I was a commit behind. Thanks

**Comment by madrazo** [comment]
I'm closing this since now it is working, but maybe they (emscropten and jsprime) can be mentioned on the README.
