### ISSUE TITLE
Telemetry Bug?

### ISSUE THREAD

**Issue by thomasuster** [haxenme/nme#476]
Hey, getting a runtime crash using NME_HXTELEMETRY 100% of the time.

* I get the crash very soon after  Telemetry initialization.
* _last_obj is accessed in hxcpp/src/hx/Telemetry.cpp which throws the runtime error, I believe _last_obj is freed before it is accessed
* It only crashes if HxScout is running before program is launched.
* If I never access _last_obj in hxcpp/src/hx/Telemetry.cpp it will not crash

I realize this might not be enough info to debug on your side. Any ideas of things I could try? I'm afraid this is a complicated IMMIX bug.

<img width="1552" alt="screen shot 2017-05-29 at 7 31 52 pm" src="https://cloud.githubusercontent.com/assets/220965/26566137/a71d4a5a-44a5-11e7-9464-191aafb689a4.png">

**Comment by hughsando** [comment]
I'm not really sure when/for how long last_obj is supposed to be valid.
One possibility is that it should be getting zeroed out more often - eg in  HXTReclaimInternal with it as obj.  Or maybe just setting it to zero by calling lookup_last_object_type()  in GCStart  or just setting it to zero  the top of HXTAfterMark.

Another possibility is some 64-bit hashing issue.  I see there is a HXCPP_TELEMETRY_DEBUG define which can be used to check this, and might be interesting to turn on.

I think if calling  lookup_last_object_type()  in GCStart  in Telemetry.cpp fixes the issue, then this is a good fix.

@jcward may have some more ideas.

**Comment by jcward** [comment]
Hmm, I haven't looked at the code to refresh my memory yet, but last_obj is an unfortunate workaround -- for some reason at the time when last_obj is set (sometime during allocation), I don't have access to all the data I need to collect (whatever is determined in lookup_last_obj). I don't recall if multi threading was implicated it not.

I think the best fix would be, determine how we can fix my implementation so I can get the data at allocation time, rather than storing the reference and checking it later.

I'll look at the code and see if I can figure out why this didn't work.

**Comment by hughsando** [comment]
I could be that in the "new" function, the vtable is not actually filled in, so you can't get the class name.
One of us would need to instrument the code after the actual allocation to handle this better - or maybe make sure the class name in passed in correctly.

**Comment by thomasuster** [comment]
For better stack trace... https://github.com/HaxeFoundation/hxcpp/issues/650

**Comment by thomasuster** [comment]
Hey I have 3 line PR that fixes the major issue. It just produces lots of unresolved types. Basically just let type==0 stay unresolved. But I'm betting @hughsando will have preferences on how types are passed for new ArrayObj, as well as telem vs. non telem. This is a show stopper for people though if you want my mini PR
