### ISSUE TITLE
D3D compiler module not found

### ISSUE THREAD

**Issue by man2** [haxenme/nme#522]
Got this when compiling bunnymark on windows 7 both neko and cpp. Resulting in black screen, nothing rendered to screen.

```
ERROR:
D3D compiler module not found.
Program has not been successfully linked.


ERR: rx::HLSLCompiler::ensureInitialized(139): D3D compiler module not found.
Bad Link.
----
VERT: uniform mat4   uTransform;
attribute vec4 aVertex;
attribute vec4 aColourArray;
varying vec4 vColourArray;
attribute vec2 aTexCoord;
varying vec2 vTexCoord;
void main()
{
   vTexCoord = aTexCoord;
   vColourArray = aColourArray;
   gl_Position = aVertex * uTransform;
}

FRAG: precision mediump float;
varying vec4 vColourArray;
uniform sampler2D uImage0;
varying vec2 vTexCoord;
void main()
{
   gl_FragColor = vColourArray*vec4(1,1,1,texture2D(uImage0,vTexCoord).a);
}

ERROR:
D3D compiler module not found.
Program has not been successfully linked.
```

**Comment by madrazo** [comment]
Hi @man2 
Which version of Windows are you in?
Please check https://github.com/haxenme/nme/issues/521

I think that for Windows <8.1 you need to add "d3dcompiler_*.dll" into the exe directory
It is found on %WindowsSdkDir%\redist\d3d
For example C:\Program Files (x86)\Windows Kits\10\Redist\D3D\x64
Reference: https://blogs.msdn.microsoft.com/chuckw/2012/05/07/hlsl-fxc-and-d3dcompile/

Also, can also disable angle with "-DNME_NO_ANGLE" when recompiling NME
I'm not sure if installing DirectX End-User Runtime Web Installer also adds d3dcompiler to the system. https://www.microsoft.com/en-us/download/details.aspx?id=35

This may be fixed by including this dll, for example, nme already includes dxguid.lib in nme\project\support\windows

**Comment by madrazo** [comment]
On the other hand,  adding
`<lib name="D3dcompiler.lib" if="NME_ANGLE"/>`
 in ToolkitBuild.xml,
and/or 
`SDL_SetHint(SDL_HINT_VIDEO_WIN_D3DCOMPILER, "1");`
in SDL2Stage.cpp

may do the trick? 

Reference: https://handmade.network/forums/t/2055-sdl2_angle_porting

**Comment by man2** [comment]
Thanks @madrazo , I'm on Windows 7. 
Adding "d3dcompiler_*.dll fixed the problem. I think many things changed on this newest release.  Still hacing issue with ogg file, I'm going to open new issue. Closing this one
