### ISSUE TITLE
[QUESTION] How accurate cubicTo method?

### ISSUE THREAD

**Issue by codeservice** [haxenme/nme#690]
I am trying to draw perfect circle using cubicTo method:

var rounderObject:Shape = new Shape();
        rounderObject.cacheAsBitmap = true;

        rounderObject.graphics.beginFill(0x0000FF);
        rounderObject.graphics.moveTo(250, 0);
        rounderObject.graphics.cubicTo(275, 0, 300, 25, 300, 50);
        rounderObject.graphics.cubicTo(300, 75, 275, 100, 250, 100);
        rounderObject.graphics.cubicTo(225, 100, 200, 75, 200, 50);
        rounderObject.graphics.cubicTo(200, 25, 225, 0, 250, 0);
        rounderObject.graphics.endFill();

        stage.addChild(rounderObject);

Result look like this:

![image](https://user-images.githubusercontent.com/1771547/102371746-86888f80-3f8c-11eb-8a1e-75739247c042.png)

Doesn't look like perfect circle. Is it issue or its impossible to draw this by using cubicTo?

**Comment by hughsando** [comment]
It is not mathematically possible to draw a circle using cubics (or quadratics), however you can get very close.
This is actually how "drawCircle" works using 8 parts instead of 4: https://github.com/haxenme/nme/blob/master/project/src/common/Graphics.cpp#L92

The trick is to optimise the control point positions using some maths that someone else worked out.

**Comment by codeservice** [comment]
Thanks! It’s exactly what I am looking for. I couldn’t find this method for
drawing rounded objects using cubic method.

Actionscript example has similar method, same as I included here.
https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/Graphics.html#cubicCurveTo()

Probably Adobe using different approach.
